namespace: namespace1
owner:
  group: JP-Next-GEN-POS-StoreOE
notify:
  slack:
    channelName: seiyu-fstgn-storeoe-ops
cloudConfig:
  azure:
    tenantId: yyyyyyy-yyyyy-yyyyy-yyyyyy
    resourceGroup: ubuntu
targets:
  - name: vmset1
    os: "UbuntuServer 20.04-LTS"
    type: azure-vm-scale-set
    scaleSetName: [vmss]
    metrics:
      - name: node
        port: 9100 
        path: /metrics
        timeout: 1s
        interval: 15s
      - name: app
        port: 8080
        path: /app1/actuator/prometheus 
        timeout: 1s
        interval: 5s
    logs:
      - name: notebook
        path: /tmp/log/notebook/*.log
      - name: system
        path: /test
stages:
  - name: dev
    refs: [main]
    cloudConfig:
      azure:
        subscriptionId: 6c7300fe-0701-437d-b954-6dcbcb876f5f
    targets:
      - name: vmset1
        metrics:
        - name: app
          interval: 30s
        logs:
        - name: notebook
          path: /var/dev/log